// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pybpyxtvoghailicquxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5YnB5eHR2b2doYWlsaWNxdXh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyODcxMTgsImV4cCI6MjA3MTg2MzExOH0.ltQQbiQPCwYboJcWkIOPuTrrxWpvyav3eMELMSjdVgY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});